version: 2.1

jobs:
  build-and-test:
    resource_class: large
    docker:
      # https://circleci.com/docs/circleci-images#language-image-variants
      # This comes with python and openjdk11
      - image: cimg/python:3.7-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
            - v6-model_cache-{{ checksum "setup.py" }}

      - restore_cache:
          keys:
            - v6-pip-cache-{{ checksum "setup.py" }}

      - run:
          name: Install EVA package with test dependencies
          command: |
            python -m venv eva_dev_env
            . eva_dev_env/bin/activate
            pip install --upgrade pip
            pip install ".[dev]"

      - run:
          name: Generate Parser Files
          command: |
            sh script/antlr4/generate_parser.sh

      - run:
          name: Test and upload coverage report to coveralls
          command: |
            . eva_dev_env/bin/activate
            sh script/test/test.sh
            coveralls

      - save_cache:
          key: v6-model_cache-{{ checksum "setup.py" }}
          paths:
            - /home/circleci/.cache/torch/hub/
            - /home/circleci/.EasyOCR/

      - save_cache:
          key: v6-pip-cache-{{ checksum "setup.py" }}
          paths:
            - ./eva_dev_env/


workflows:
  main:
    jobs:
      - build-and-test
